
public enum TokenType
{
	SPACE, NEWLINE, LEFT_BRACE, RIGHT_BRACE, LEFT_PARENTHESIS, RIGHT_PARENTHESIS, 
	EQUALS, NOT, SEMICOLON, KEYWORD_IF, KEYWORD_ELSE, KEYWORD_TRUE, KEYWORD_FALSE,
	IDENTIFIER, INVALID
}
